name: Bot Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    name: BOTPM
    runs-on: ubuntu-latest
    
    steps:
      - name: clone source
        run: |
          git config --global user.email nasutionmiku@gmail.com
          git config --global user.name Shiivam69
          git clone https://Shiivam69:$GH_TOKEN@github.com/Shiivam69/BOTPM -b main
          cd BOTPM
          curl $CONFIG_FILE_URL -o config.env
        env:
         GH_TOKEN: ${{secrets.GH_TOKEN}}
         CONFIG_FILE_URL: ${{secrets.CONFIG}}

      - name: Run Bot..
        run: |
          cd BOTPM
          apt-get update && apt-get upgrade -y
          pip install -U -r requirements.txt
          python3 bot.py
          bash start &
          sleep 300m
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
